FORMAT: 1A
HOST: http://api.eventance.com/

# Eventance

Eventance public API.

# Auth [/]

Token-based authorization.

### API Token create [POST /api-token-auth/]
    
+ Request

            {
                "username": "test",
                "password": "test"
            }

+ Response 200 (application/json)

            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwib3JpZ19pYXQiOjE0MzEzMzU1MjgsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNDM5MzM1NTI4fQ.s84IiGYLz649KILx2NfZ7KfLk928xcLJvMC2mNlXB6Q"
            }

+ Response 400 (application/json)

            {
                "non_field_errors": [
                    "Unable to login with provided credentials."
                ]
            }
        
### API Token refresh [POST /api-token-refresh/]

+ Request
    
            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwib3JpZ19pYXQiOjE0MzEzMzU1MjgsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNDM5MzM1NTI4fQ.s84IiGYLz649KILx2NfZ7KfLk928xcLJvMC2mNlXB6Q"
            }
    
+ Response 200 (application/json)
    
            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwib3JpZ19pYXQiOjE0MzEzMzU1MjgsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNDM5MzM1NTI4fQ.s84IiGYLz649KILx2NfZ7KfLk928xcLJvMC2mNlXB6Q"
            }

+ Response 400 (application/json)

            {
                "non_field_errors": [
                    "Error decoding signature."
                ]
            }
        
### API Token verfy [POST /api-token-verify/]

+ Request
    
            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwib3JpZ19pYXQiOjE0MzEzMzU1MjgsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNDM5MzM1NTI4fQ.s84IiGYLz649KILx2NfZ7KfLk928xcLJvMC2mNlXB6Q"
            }
    
+ Response 200 (application/json)
    
            {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwib3JpZ19pYXQiOjE0MzEzMzU1MjgsInVzZXJfaWQiOjEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIiwiZXhwIjoxNDM5MzM1NTI4fQ.s84IiGYLz649KILx2NfZ7KfLk928xcLJvMC2mNlXB6Q"
            }

+ Response 400 (application/json)

            {
                "non_field_errors": [
                    "Error decoding signature."
                ]
            }
        
# Group [/api/1.0/club/{club_id}/staff-group/]

The group API

### Group create [POST]

+ Parameters
    + club_id (required, int) ... staff's club

+ Request
    + Headers
    
            Authorization: JWT [token]

    + Body
        
            {
                "name": "The group name"
            }

+ Response 200 (application/json)
    
            {
                "id": 1,
                "club": "http://localhost:8000/api/1.0/club/1",
                "name": "The group name"
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }
            
+ Response 409 (text/html)
            
            CONFLICT: duplicated object

### Group list [GET]

+ Request
    + Headers
    
            Authorization: JWT [token]


+ Response 200 (application/json)

            {
                "count": 2,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 1,
                        "club": "http://localhost:8000/api/1.0/club/1",
                        "name": "Camareros"
                    },
                    {
                        "id": 2,
                        "club": "http://localhost:8000/api/1.0/club/1",
                        "name": "Seguridad"
                    }
                ]
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }
            
# Club [/api/1.0/club/]

The club API

### Club create [POST]

+ Request
    + Headers
    
            Authorization: JWT [token]

    + Body
        
            {
                "name": "MyClub"
            }
            
+ Response 200 (application/json)

            {
                "id": 3,
                "name": "MyClub",
                "logo": "",
                "removed": false
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

+ Response 401 (text/html)

            CONFLICT: duplicated object

### Club list [GET]

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                "count": 2,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 1,
                        "name": "TheOne",
                        "logo": "sdfsd",
                        "removed": false
                    },
                    {
                        "id": 2,
                        "name": "SDFsa",
                        "logo": "sdfds",
                        "removed": false
                    }
                ]
            }
            
+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }
            
### Club detail [GET /api/1.0/club/{club_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                "id": 1,
                "name": "TheOne",
                "logo": "none",
                "removed": false
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

### Club update [PATCH /api/1.0/club/{club_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id

+ Request
    + Headers
    
            Authorization: JWT [token]
    + Body

            {
                "name": "Verdant",
                "logo": "still none",
            }

+ Response 200 (application/json)

            {
                "id": 1,
                "name": "Verdant",
                "logo": "still none",
                "removed": false
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

### Club delete [DELETE /api/1.0/club/{club_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 204 (application/json)

# Zone [/api/1.0/club/{club_id}/zone/]

The zone API

### Zone create [POST]

+ Parameters
    + club_id (required, int) ... Selected club id

+ Request
    + Headers
    
            Authorization: JWT [token]

    + Body
        
            {
                "name": "Zone 01"
            }
            
+ Response 200 (application/json)

            {
                "id": 1,
                "club": "http://localhost:8000/api/1.0/club/1",
                "name": "Zone 01"
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

+ Response 401 (text/html)

            CONFLICT: duplicated object

### Zone list [GET]

+ Parameters
    + club_id (required, int) ... Selected club id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                "count": 1,
                "next": null,
                "previous": null,
                "results": [
                    {
                        "id": 1,
                        "club": "http://localhost:8000/api/1.0/club/1",
                        "name": "Zone 01"
                    }
                ]
            }
            
+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

### Zone update [PATCH /api/1.0/club/{club_id}/zone/{zone_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + zone_id (required, int) ... Selected zone id

+ Request
    + Headers
    
            Authorization: JWT [token]
    + Body

            {
                "name": "Zone 02"
            }

+ Response 200 (application/json)

            {
                "id": 1,
                "club": "http://localhost:8000/api/1.0/club/1",
                "name": "Zona 02"
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

### Zone delete [DELETE /api/1.0/club/{club_id}/zone/{zone_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + zone_id (required, int) ... Selected zone id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 204 (application/json)

# Staff [/api/1.0/club/{club_id}/staff/]

The staff API

### Staff create [POST]

+ Request
    + Headers
    
            Authorization: JWT [token]

    + Body
        
            {
                "club": 1,
                "user": 1,
                "group": 1,
                "permissions": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                ]
            }
            
+ Response 200 (application/json)

            {
                "id": 3,
                "club": "http://localhost:8000/api/1.0/club/1",
                "user": 1,
                "group": 3,
                "permissions": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                ]
            }

+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }

+ Response 401 (text/html)

            CONFLICT: duplicated object

### Staff list [GET]

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
            "count": 3,
            "next": null,
            "previous": null,
            "results": [
                {
                    "id": 1,
                    "club": "http://localhost:8000/api/1.0/club/1",
                    "user": 1,
                    "group": 1,
                    "permissions": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10
                    ]
                }
            ]
        }
            
+ Response 401 (application/json)

            {
                "detail": "Las credenciales de autenticación no se proveyeron."
            }
            
### Staff detail [GET /api/1.0/club/{club_id}/staff/{staff_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + staff_id (required, int) ... Selected staff id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                "id": 1,
                "club": "http://localhost:8000/api/1.0/club/1",
                "user": 1,
                "group": 1,
                "permissions": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10
                ]
            }

+ Response 401 (text/html)

            You are not allowed to access the content

### Staff update [PATCH /api/1.0/club/{club_id}/staff/{staff_id}/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + staff_id (required, int) ... Selected staff id

+ Request
    + Headers
    
            Authorization: JWT [token]
    + Body

            {
                "group": 2,
                "permissions": [
                    4,
                    5
                ]
            }

+ Response 200 (application/json)

            {
                "id": 1,
                "club": "http://localhost:8000/api/1.0/club/1",
                "user": 1,
                "group": 2,
                "permissions": [
                    4,
                    5
                ]
            }

+ Response 401 (text/html)

            You are not allowed to access the content

### Staff events [GET /api/1.0/club/{club_id}/staff/{staff_id}/event/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + staff_id (required, int) ... Selected staff id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                TODO - NOT IMPLEMENTED YET
            }

+ Response 401 (text/html)

            You are not allowed to access the content

+ Response 404 (text/html)

            StaffEvent matching query does not exist.

### Staff sessions [GET /api/1.0/club/{club_id}/staff/{staff_id}/session/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + staff_id (required, int) ... Selected staff id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            {
                TODO - NOT IMPLEMENTED YET
            }

+ Response 401 (text/html)

            You are not allowed to access the content

+ Response 404 (text/html)

            StaffSession matching query does not exist.

### Staff stats [GET /api/1.0/club/{club_id}/staff/{staff_id}/stats/]

+ Parameters
    + club_id (required, int) ... Selected club id
    + staff_id (required, int) ... Selected staff id

+ Request
    + Headers
    
            Authorization: JWT [token]

+ Response 200 (application/json)

            TODO - NEEDS DEFINITION

+ Response 401 (text/html)

            You are not allowed to access the content

+ Response 404 (text/html)

            StaffSession matching query does not exist.
