FORMAT: 1A
HOST: http://api.eventance.com/

# Eventance

Eventance public API.

# Group Club

## Collection [/club]

### Retrieve the Club list [GET]

+ Response 200 (application/json)

        {
            "questions_url": "/questions"
        }
        
### Create a Club [POST]

+ Response 201 (application/json)

        {
            "questions_url": "/questions"
        }
        
## Entity [/club/{id}]

### Retrive an specific club [GET]
+ Parameters
    + id (string) ... Id
+ Response 200 (application/json)

        {
            "questions_url": "/questions"
        }
        
### Delete a club [DELETE]
+ Parameters
    + id (string) ... Id
+ Response 201 (application/json)

        {
            "questions_url": "/questions"
        }
